server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArunaDon/tagd-configsrv-repo.git
          default-label: master
          username: arunadon
          password: '{cipher}f61b05279c1718123e4216ff32a94bbf62af8b21d69b02c153a7e9c07fc319b15118aa08a9ce335383e8a2a981ad8b0f8868e1a5fd5d842810c5f498f64d4a30'
          clone-on-start: true
      bootstrap: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}c05c309e0c5e79cc1747f0f808aec055a2fba38cfc74a153515da551286353215dd82e6ccffba93c09b128ff75bf440d'

encrypt:
  key: Demo_Pwd!2020